spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootMysql?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

